version: '3.8'
services:
  app:
    build: .
    ports:
      - "9898:9898"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge